# Generated by Django 4.0.3 on 2022-03-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_rename_clientcount_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fname',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='lname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='place',
            field=models.CharField(default='', max_length=20),
        ),
    ]
